# Generated by Django 2.0 on 2019-05-22 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_id', to=settings.AUTH_USER_MODEL, verbose_name='心愿者'),
        ),
        migrations.AddField(
            model_name='gift',
            name='bookid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_book', to='books.Book', verbose_name='书籍'),
        ),
        migrations.AddField(
            model_name='gift',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_user', to=settings.AUTH_USER_MODEL, verbose_name='赠送者'),
        ),
    ]
