# Generated by Django 2.0 on 2019-05-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190522_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=20, verbose_name='收件人')),
                ('address', models.CharField(max_length=100, verbose_name='书籍收件地址')),
                ('message', models.CharField(max_length=200, verbose_name='留言')),
                ('mobile', models.CharField(max_length=20, verbose_name='联系电话')),
                ('isbn', models.CharField(max_length=13, verbose_name='isbn')),
                ('book_title', models.CharField(max_length=50, verbose_name='书名')),
                ('book_author', models.CharField(max_length=30, verbose_name='作者')),
                ('book_img', models.ImageField(upload_to='uploads/book/%Y/%m', verbose_name='书籍图片')),
                ('requester_id', models.IntegerField(default=0, verbose_name='请求者id')),
                ('requester_nickname', models.CharField(max_length=20, verbose_name='请求者昵称')),
                ('gifter_id', models.IntegerField(default=0, verbose_name='赠送者id')),
                ('gift_id', models.IntegerField(default=0, verbose_name='赠送清单id')),
                ('gifter_nickname', models.CharField(max_length=20, verbose_name='赠送者昵称')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '鱼漂',
                'verbose_name_plural': '鱼漂',
                'db_table': 'drift',
            },
        ),
    ]
