# Generated by Django 2.0 on 2019-05-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_drift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='launched',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='launched',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
    ]
