# Generated by Django 2.0 on 2019-05-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderinfo',
            table='orderInfo',
        ),
    ]
