# Generated by Django 2.0 on 2019-05-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(default='10000000001', max_length=11, unique=True, verbose_name='手机号码'),
        ),
    ]
